//**************************************************************************
//         Copyright (c) , Inc . All rights reserved.
//         STB/SA, all right reserved.
//
//	Product	: STB Firmware
//
//	Date		: 
//	Author		: 
//	Purpose	: Provide STBC Control 
//	Sources	: 
//***************************************************************************
//
// Modification use :
//**************************************************************************
//	Update
//
//	Date  	: 
//	Name	: 
//	Description	: 
//
//	Item			                  Source
//   ----------------------------------------		-------------------

#ifndef __REG_DRV_STBC_H__
#define __REG_DRV_STBC_H__
#include "drv_config.h"

#if (CONFIG_CHIP_MODLE == NT78310)    
#include "def_type.h"
#include "def_err.h"

/*******************************************************************************************/
/* control registers */
#define	ADR_STBC_CTRL_BASE				(0xB4013000)
/*******************************************************************************************/
/* RTC ADDR */
#define	ADR_STBC_RTC_CTRL_BASE			(ADR_STBC_CTRL_BASE + 0x00000000)			//ADR_RTC_CTRL_START
#define	ADR_STBC_RTC_TIMER_BASE			(ADR_STBC_RTC_CTRL_BASE + 0x00000000)       //ADR_STBC_RTC_TIMER_BASE
#define	ADR_STBC_RTC_CNT				(ADR_STBC_RTC_CTRL_BASE + 0x00000004)       //ADR_STBC_RTC_CNT
#define	ADR_STBC_RTC_CNT_CTRL			(ADR_STBC_RTC_CTRL_BASE + 0x00000008)       //ADR_STBC_RTC_CNT_CTRL
#define	ADR_STBC_RTC_INT_CTRL			(ADR_STBC_RTC_CTRL_BASE + 0x0000000C)       //ADR_STBC_RTC_INT_CTRL
#define	ADR_STBC_RTC_INT_STS			(ADR_STBC_RTC_CTRL_BASE + 0x00000010)       //ADR_STBC_RTC_INT_STS
#define	ADR_STBC_RTC_WRITE_PROTECT		(ADR_STBC_RTC_CTRL_BASE + 0x00000020)       //ADR_STBC_RTC_WRITE_PROTECT
#define	ADR_STBC_RTC_ITL_SRC_DIV		(ADR_STBC_RTC_CTRL_BASE + 0x00000024)       //ADR_STBC_RTC_ITL_SRC_DIV
#define	ADR_STBC_RTC_RESERVED			(ADR_STBC_RTC_CTRL_BASE + 0x00000028)       //ADR_STBC_RTC_RESERVED
#define	ADR_STBC_RTC_DOWN_CNT_CTRL		(ADR_STBC_RTC_CTRL_BASE + 0x0000002C)       //ADR_STBC_RTC_DOWN_CNT_CTRL
#define	ADR_STBC_RTC_DOWN_CNT_NUM_CTRL	(ADR_STBC_RTC_CTRL_BASE + 0x00000030)       //ADR_STBC_RTC_DOWN_CNT_NUM_CTRL
#define	ADR_STBC_RTC_DOWN_CNT_NUM		(ADR_STBC_RTC_CTRL_BASE + 0x00000034)       //ADR_STBC_RTC_DOWN_CNT_NUM
#define	ADR_STBC_INT_GROUP				(ADR_STBC_RTC_CTRL_BASE + 0x00000038)       //ADR_STBC_STBC_INT_GROUP

/*******************************************************************************************/
/* IR ADDR */
#define	ADR_STBC_IR_CTRL_BASE			(ADR_STBC_CTRL_BASE + 0x00000100)			//ADR_IR_CTRL_START
#define	ADR_STBC_IR_DEC_CTRL			(ADR_STBC_IR_CTRL_BASE + 0x00000000)		//ADR_STBC_IR_DEC_CTRL
#define	ADR_STBC_IR_DEC_STS				(ADR_STBC_IR_CTRL_BASE + 0x00000004)		//ADR_STBC_IR_DEC_STS
#define	ADR_STBC_IR_FORMAT				(ADR_STBC_IR_CTRL_BASE + 0x00000008)		//ADR_STBC_IR_FORMAT
#define	ADR_STBC_IR_HEAD_PULSE_TIME		(ADR_STBC_IR_CTRL_BASE + 0x0000000C)		//ADR_STBC_IR_HEAD_PULSE_TIME
#define	ADR_STBC_IR_HEAD_SPACE_TIME		(ADR_STBC_IR_CTRL_BASE + 0x00000010)       	//ADR_STBC_IR_HEAD_SPACE_TIME
#define	ADR_STBC_IR_LOG0_PULSE_TIME		(ADR_STBC_IR_CTRL_BASE + 0x00000014)       	//ADR_STBC_IR_LOG0_PULSE_TIME
#define	ADR_STBC_IR_LOG0_SPACE_TIME		(ADR_STBC_IR_CTRL_BASE + 0x00000018)       	//ADR_STBC_IR_LOG0_SPACE_TIME
#define	ADR_STBC_IR_LOG1_PULSE_TIME		(ADR_STBC_IR_CTRL_BASE + 0x0000001C)       	//ADR_STBC_IR_LOG1_PULSE_TIME
#define	ADR_STBC_IR_LOG1_SPACE_TIME		(ADR_STBC_IR_CTRL_BASE + 0x00000020)       	//ADR_STBC_IR_LOG1_SPACE_TIME
#define	ADR_STBC_IR_GLITCH_TIME			(ADR_STBC_IR_CTRL_BASE + 0x00000030)       	//ADR_STBC_IR_GLITCH_TIME
#define	ADR_STBC_IR_REPCOD_PULSE_TIME	(ADR_STBC_IR_CTRL_BASE + 0x00000034)       	//ADR_STBC_IR_REPCOD_PULSE_TIME
#define	ADR_STBC_IR_REPCOD_SPACE_TIME	(ADR_STBC_IR_CTRL_BASE + 0x00000038)       	//ADR_STBC_IR_REPCOD_SPACE_TIME
#define	ADR_STBC_IR_REC_LOW_WORD_FIFO	(ADR_STBC_IR_CTRL_BASE + 0x0000003C)       	//ADR_STBC_IR_REC_LOW_WORD_FIFO
#define	ADR_STBC_IR_REC_HIGH_WORD_FIFO	(ADR_STBC_IR_CTRL_BASE + 0x00000040)       	//ADR_STBC_IR_REC_HIGH_WORD_FIFO
#define	ADR_STBC_IR_WAKEUP_LOW_WORD		(ADR_STBC_IR_CTRL_BASE + 0x00000044)       	//ADR_STBC_IR_WAKEUP_LOW_WORD
#define	ADR_STBC_PAD1					(ADR_STBC_IR_CTRL_BASE + 0x00000048)       	//ADR_STBC_PAD1
#define	ADR_STBC_PAD2					(ADR_STBC_IR_CTRL_BASE + 0x0000004C)       	//ADR_STBC_PAD2
#define	ADR_STBC_IR_BIPHASE_TIME		(ADR_STBC_IR_CTRL_BASE + 0x00000050)       	//ADR_STBC_IR_BIPHASE_TIME


/*******************************************************************************************/
/* PBC ADDR */
#define	ADR_STBC_PBC_CTRL_BASE				(ADR_STBC_CTRL_BASE + 0x00000200)			//ADR_STBC_PBC_CTRL_BASE
#define	ADR_STBC_PBC_CTRL_STS				(ADR_STBC_PBC_CTRL_BASE + 0x00000000)       //ADR_STBC_PBC_CTRL_STS
#define	ADR_STBC_PBC_RST_DELAY_CNT			(ADR_STBC_PBC_CTRL_BASE + 0x00000004)       //ADR_STBC_PBC_RST_DELAY_CNT
#define	ADR_STBC_PBC_INPUT_CTRL_SIGNAL		(ADR_STBC_PBC_CTRL_BASE + 0x00000008)       //ADR_STBC_PBC_INPUT_CTRL_SIGNAL
#define	ADR_STBC_PBC_VER_EDITION			(ADR_STBC_PBC_CTRL_BASE + 0x0000000C)       //ADR_STBC_PBC_LD0_INI_STS
#define	ADR_STBC_IO_LEV_INPUT_OUTPUT_SEL	(ADR_STBC_PBC_CTRL_BASE + 0x00000010)       //ADR_STBC_IO_LEV_INPUT_OUTPUT_SEL
#define	ADR_STBC_IO_DIR_SEL					(ADR_STBC_PBC_CTRL_BASE + 0x00000014)       //ADR_STBC_IO_DIR_SEL
#define	ADR_STBC_GPIO_FUN_SEL				(ADR_STBC_PBC_CTRL_BASE + 0x00000018)       //ADR_STBC_GPIO_FUN_SEL


/* CEC ADDR */
#define	ADR_STBC_CEC_CTRL_BASE			(ADR_STBC_CTRL_BASE + 0x00000300)			//ADR_STBC_CEC_CTRL_BASE
#define	ADR_STBC_CEC_CTRL				(ADR_STBC_CEC_CTRL_BASE + 0x00000000)       //ADR_STBC_CEC_CTRL
#define	ADR_STBC_CEC_CLK_BASE1			(ADR_STBC_CEC_CTRL_BASE + 0x00000004)       //ADR_STBC_CEC_CLK_BASE1
#define	ADR_STBC_CEC_CLK_BASE2			(ADR_STBC_CEC_CTRL_BASE + 0x00000008)       //ADR_STBC_CEC_CLK_BASE2
#define	ADR_STBC_CEC_SIGFREE_CNT1		(ADR_STBC_CEC_CTRL_BASE + 0x0000000C)       //ADR_STBC_CEC_SIGFREE_CNT1
#define	ADR_STBC_CEC_SIGFREE_CNT2		(ADR_STBC_CEC_CTRL_BASE + 0x00000010)       //ADR_STBC_CEC_SIGFREE_CNT2
#define	ADR_STBC_CEC_TX_RISEEDGE		(ADR_STBC_CEC_CTRL_BASE + 0x00000014)       //ADR_STBC_CEC_TX_RISEEDGE
#define	ADR_STBC_CEC_TX_FALLEDGE		(ADR_STBC_CEC_CTRL_BASE + 0x00000018)       //ADR_STBC_CEC_TX_FALLEDGE
#define	ADR_STBC_CEC_RX_STARTBIT_EDGE	(ADR_STBC_CEC_CTRL_BASE + 0x0000001C)       //ADR_STBC_CEC_RX_STARTBIT_EDGE
#define	ADR_STBC_CEC_RX_DATABIT_EDGE	(ADR_STBC_CEC_CTRL_BASE + 0x00000020)       //ADR_STBC_CEC_RX_DATABIT_EDGE
#define	ADR_STBC_CEC_RX_SAFE_SMPDATA	(ADR_STBC_CEC_CTRL_BASE + 0x00000024)       //ADR_STBC_CEC_RX_SAFE_SMPDATA
#define	ADR_STBC_CEC_DEGLITCH_FTR		(ADR_STBC_CEC_CTRL_BASE + 0x00000028)       //ADR_STBC_CEC_DEGLITCH_FTR
#define	ADR_STBC_CEC_RX_LOWERR_LSB		(ADR_STBC_CEC_CTRL_BASE + 0x0000002C)       //ADR_STBC_CEC_RX_LOWERR_LSB
#define	ADR_STBC_CEC_RX_LOWERR_MSB		(ADR_STBC_CEC_CTRL_BASE + 0x00000030)       //ADR_STBC_CEC_RX_LOWERR_MSB
#define	ADR_STBC_CEC_INT_EN				(ADR_STBC_CEC_CTRL_BASE + 0x00000034)       //ADR_STBC_CEC_INT_EN
#define	ADR_STBC_CEC_INT_DIS			(ADR_STBC_CEC_CTRL_BASE + 0x00000038)       //ADR_STBC_CEC_INT_DIS
#define	ADR_STBC_CEC_INT_FLAG			(ADR_STBC_CEC_CTRL_BASE + 0x0000003C)       //ADR_STBC_CEC_INT_FLAG
#define	ADR_STBC_CEC_DBG				(ADR_STBC_CEC_CTRL_BASE + 0x00000040)       //ADR_STBC_CEC_DBG
#define	ADR_STBC_CEC_RX_ADDR_EN1		(ADR_STBC_CEC_CTRL_BASE + 0x00000044)       //ADR_STBC_CEC_RX_ADDR_EN1
#define	ADR_STBC_CEC_RX_ADDR_EN2		(ADR_STBC_CEC_CTRL_BASE + 0x00000048)       //ADR_STBC_CEC_RX_ADDR_EN2
#define	ADR_STBC_CEC_RX_FRAME_LEN		(ADR_STBC_CEC_CTRL_BASE + 0x0000004C)       //ADR_STBC_CEC_RX_FRAME_LEN
#define	ADR_STBC_CEC_TX_FRAME_LEN		(ADR_STBC_CEC_CTRL_BASE + 0x00000050)       //ADR_STBC_CEC_TX_FRAME_LEN
#define	ADR_STBC_CEC_FTR				(ADR_STBC_CEC_CTRL_BASE + 0x00000054)       //ADR_STBC_CEC_FTR
#define	ADR_STBC_CEC_TX_DATA0			(ADR_STBC_CEC_CTRL_BASE + 0x00000060)       //ADR_STBC_CEC_TX_DATA0
#define	ADR_STBC_CEC_TX_DATA1			(ADR_STBC_CEC_CTRL_BASE + 0x00000064)       //ADR_STBC_CEC_TX_DATA1
#define	ADR_STBC_CEC_TX_DATA2			(ADR_STBC_CEC_CTRL_BASE + 0x00000068)       //ADR_STBC_CEC_TX_DATA2
#define	ADR_STBC_CEC_TX_DATA3			(ADR_STBC_CEC_CTRL_BASE + 0x0000006C)       //ADR_STBC_CEC_TX_DATA3
#define	ADR_STBC_CEC_TX_DATA4			(ADR_STBC_CEC_CTRL_BASE + 0x00000070)       //ADR_STBC_CEC_TX_DATA4
#define	ADR_STBC_CEC_TX_DATA5			(ADR_STBC_CEC_CTRL_BASE + 0x00000074)       //ADR_STBC_CEC_TX_DATA5
#define	ADR_STBC_CEC_TX_DATA6			(ADR_STBC_CEC_CTRL_BASE + 0x00000078)       //ADR_STBC_CEC_TX_DATA6
#define	ADR_STBC_CEC_TX_DATA7			(ADR_STBC_CEC_CTRL_BASE + 0x0000007C)       //ADR_STBC_CEC_TX_DATA7
#define	ADR_STBC_CEC_TX_DATA8			(ADR_STBC_CEC_CTRL_BASE + 0x00000080)       //ADR_STBC_CEC_TX_DATA8
#define	ADR_STBC_CEC_TX_DATA9			(ADR_STBC_CEC_CTRL_BASE + 0x00000084)       //ADR_STBC_CEC_TX_DATA9
#define	ADR_STBC_CEC_TX_DATA10			(ADR_STBC_CEC_CTRL_BASE + 0x00000088)       //ADR_STBC_CEC_TX_DATA10
#define	ADR_STBC_CEC_TX_DATA11			(ADR_STBC_CEC_CTRL_BASE + 0x0000008C)       //ADR_STBC_CEC_TX_DATA11
#define	ADR_STBC_CEC_TX_DATA12			(ADR_STBC_CEC_CTRL_BASE + 0x00000090)       //ADR_STBC_CEC_TX_DATA12
#define	ADR_STBC_CEC_TX_DATA13			(ADR_STBC_CEC_CTRL_BASE + 0x00000094)       //ADR_STBC_CEC_TX_DATA13
#define	ADR_STBC_CEC_TX_DATA14			(ADR_STBC_CEC_CTRL_BASE + 0x00000098)       //ADR_STBC_CEC_TX_DATA14
#define	ADR_STBC_CEC_TX_DATA15			(ADR_STBC_CEC_CTRL_BASE + 0x0000009C)       //ADR_STBC_CEC_TX_DATA15
#define	ADR_STBC_CEC_TX_DATA16			(ADR_STBC_CEC_CTRL_BASE + 0x000000A0)       //ADR_STBC_CEC_TX_DATA16
#define	ADR_STBC_CEC_RX_DATA0			(ADR_STBC_CEC_CTRL_BASE + 0x000000B0)       //ADR_STBC_CEC_RX_DATA0
#define	ADR_STBC_CEC_RX_DATA1			(ADR_STBC_CEC_CTRL_BASE + 0x000000B4)       //ADR_STBC_CEC_RX_DATA1
#define	ADR_STBC_CEC_RX_DATA2			(ADR_STBC_CEC_CTRL_BASE + 0x000000B8)       //ADR_STBC_CEC_RX_DATA2
#define	ADR_STBC_CEC_RX_DATA3			(ADR_STBC_CEC_CTRL_BASE + 0x000000BC)       //ADR_STBC_CEC_RX_DATA3
#define	ADR_STBC_CEC_RX_DATA4			(ADR_STBC_CEC_CTRL_BASE + 0x000000C0)       //ADR_STBC_CEC_RX_DATA4
#define	ADR_STBC_CEC_RX_DATA5			(ADR_STBC_CEC_CTRL_BASE + 0x000000C4)       //ADR_STBC_CEC_RX_DATA5
#define	ADR_STBC_CEC_RX_DATA6			(ADR_STBC_CEC_CTRL_BASE + 0x000000C8)       //ADR_STBC_CEC_RX_DATA6
#define	ADR_STBC_CEC_RX_DATA7			(ADR_STBC_CEC_CTRL_BASE + 0x000000CC)       //ADR_STBC_CEC_RX_DATA7
#define	ADR_STBC_CEC_RX_DATA8			(ADR_STBC_CEC_CTRL_BASE + 0x000000D0)       //ADR_STBC_CEC_RX_DATA8
#define	ADR_STBC_CEC_RX_DATA9			(ADR_STBC_CEC_CTRL_BASE + 0x000000D4)       //ADR_STBC_CEC_RX_DATA9
#define	ADR_STBC_CEC_RX_DATA10			(ADR_STBC_CEC_CTRL_BASE + 0x000000D8)       //ADR_STBC_CEC_RX_DATA10
#define	ADR_STBC_CEC_RX_DATA11			(ADR_STBC_CEC_CTRL_BASE + 0x000000DC)       //ADR_STBC_CEC_RX_DATA11
#define	ADR_STBC_CEC_RX_DATA12			(ADR_STBC_CEC_CTRL_BASE + 0x000000E0)       //ADR_STBC_CEC_RX_DATA12
#define	ADR_STBC_CEC_RX_DATA13			(ADR_STBC_CEC_CTRL_BASE + 0x000000E4)       //ADR_STBC_CEC_RX_DATA13
#define	ADR_STBC_CEC_RX_DATA14			(ADR_STBC_CEC_CTRL_BASE + 0x000000E8)       //ADR_STBC_CEC_RX_DATA14
#define	ADR_STBC_CEC_RX_DATA15			(ADR_STBC_CEC_CTRL_BASE + 0x000000EC)       //ADR_STBC_CEC_RX_DATA15
#define	ADR_STBC_CEC_RX_DATA16			(ADR_STBC_CEC_CTRL_BASE + 0x000000F0)       //ADR_STBC_CEC_RX_DATA16


/*******************************************************************************************/
/* RTC REG */
#define	REG_STBC_RTC_TIMER_BASE			(*((vu32 *)ADR_STBC_RTC_TIMER_BASE			))       //REG_STBC_RTC_TIMER_BASE
#define	REG_STBC_RTC_CNT				(*((vu32 *)ADR_STBC_RTC_CNT					))       //REG_STBC_RTC_CNT
#define	REG_STBC_RTC_CNT_CTRL			(*((vu32 *)ADR_STBC_RTC_CNT_CTRL			))       //REG_STBC_RTC_CNT_CTRL
#define	REG_STBC_RTC_INT_CTRL			(*((vu32 *)ADR_STBC_RTC_INT_CTRL			))       //REG_STBC_RTC_INT_CTRL
#define	REG_STBC_RTC_INT_STS			(*((vu32 *)ADR_STBC_RTC_INT_STS				))       //REG_STBC_RTC_INT_STS
#define	REG_STBC_RTC_WRITE_PROTECT		(*((vu32 *)ADR_STBC_RTC_WRITE_PROTECT		))       //REG_STBC_RTC_WRITE_PROTECT
#define	REG_STBC_RTC_ITL_SRC_DIV		(*((vu32 *)ADR_STBC_RTC_ITL_SRC_DIV			))       //REG_STBC_RTC_ITL_SRC_DIV
#define	REG_STBC_RTC_RESERVED			(*((vu32 *)ADR_STBC_RTC_RESERVED			))       //REG_STBC_RTC_RESERVED
#define	REG_STBC_RTC_DOWN_CNT_CTRL		(*((vu32 *)ADR_STBC_RTC_DOWN_CNT_CTRL		))       //REG_STBC_RTC_DOWN_CNT_CTRL
#define	REG_STBC_RTC_DOWN_CNT_NUM_CTRL	(*((vu32 *)ADR_STBC_RTC_DOWN_CNT_NUM_CTRL	))       //REG_STBC_RTC_DOWN_CNT_NUM_CTRL
#define	REG_STBC_RTC_DOWN_CNT_NUM		(*((vu32 *)ADR_STBC_RTC_DOWN_CNT_NUM		))       //REG_STBC_RTC_DOWN_CNT_NUM
#define	REG_STBC_INT_GROUP				(*((vu32 *)ADR_STBC_INT_GROUP				))       //REG_STBC_INT_GROUP

/*******************************************************************************************/
/* IR REG */
#define	REG_STBC_IR_DEC_CTRL			(*((vu32 *)ADR_STBC_IR_DEC_CTRL				))       //REG_STBC_IR_DEC_CTRL
#define	REG_STBC_IR_DEC_STS				(*((vu32 *)ADR_STBC_IR_DEC_STS				))       //REG_STBC_IR_DEC_STS
#define	REG_STBC_IR_FORMAT				(*((vu32 *)ADR_STBC_IR_FORMAT				))       //REG_STBC_IR_FORMAT
#define	REG_STBC_IR_HEAD_PULSE_TIME		(*((vu32 *)ADR_STBC_IR_HEAD_PULSE_TIME		))       //REG_STBC_IR_HEAD_PULSE_TIME
#define	REG_STBC_IR_HEAD_SPACE_TIME		(*((vu32 *)ADR_STBC_IR_HEAD_SPACE_TIME		))       //REG_STBC_IR_HEAD_SPACE_TIME
#define	REG_STBC_IR_LOG0_PULSE_TIME		(*((vu32 *)ADR_STBC_IR_LOG0_PULSE_TIME		))       //REG_STBC_IR_LOG0_PULSE_TIME
#define	REG_STBC_IR_LOG0_SPACE_TIME		(*((vu32 *)ADR_STBC_IR_LOG0_SPACE_TIME		))       //REG_STBC_IR_LOG0_SPACE_TIME
#define	REG_STBC_IR_LOG1_PULSE_TIME		(*((vu32 *)ADR_STBC_IR_LOG1_PULSE_TIME		))       //REG_STBC_IR_LOG1_PULSE_TIME
#define	REG_STBC_IR_LOG1_SPACE_TIME		(*((vu32 *)ADR_STBC_IR_LOG1_SPACE_TIME		))       //REG_STBC_IR_LOG1_SPACE_TIME
#define	REG_STBC_IR_GLITCH_TIME			(*((vu32 *)ADR_STBC_IR_GLITCH_TIME			))       //REG_STBC_IR_GLITCH_TIME
#define	REG_STBC_IR_REPCOD_PULSE_TIME	(*((vu32 *)ADR_STBC_IR_REPCOD_PULSE_TIME	))       //REG_STBC_IR_REPCOD_PULSE_TIME
#define	REG_STBC_IR_REPCOD_SPACE_TIME	(*((vu32 *)ADR_STBC_IR_REPCOD_SPACE_TIME	))       //REG_STBC_IR_REPCOD_SPACE_TIME
#define	REG_STBC_IR_REC_LOW_WORD_FIFO	(*((vu32 *)ADR_STBC_IR_REC_LOW_WORD_FIFO	))       //REG_STBC_IR_REC_LOW_WORD_FIFO
#define	REG_STBC_IR_REC_HIGH_WORD_FIFO	(*((vu32 *)ADR_STBC_IR_REC_HIGH_WORD_FIFO	))       //REG_STBC_IR_REC_HIGH_WORD_FIFO
#define	REG_STBC_IR_WAKEUP_LOW_WORD		(*((vu32 *)ADR_STBC_IR_WAKEUP_LOW_WORD		))       //REG_STBC_IR_WAKEUP_LOW_WORD
#define	REG_STBC_PAD1					(*((vu32 *)ADR_STBC_PAD1					))       //REG_STBC_PAD1
#define	REG_STBC_PAD2					(*((vu32 *)ADR_STBC_PAD2					))       //REG_STBC_PAD2
#define	REG_STBC_IR_BIPHASE_TIME		(*((vu32 *)ADR_STBC_IR_BIPHASE_TIME			))       //REG_STBC_IR_BIPHASE_TIME

/*******************************************************************************************/
/* PBC REG */
#define	REG_STBC_PBC_CTRL_STS				(*((vu32 *)ADR_STBC_PBC_CTRL_STS			))       //REG_STBC_PBC_CTRL_STS
#define	REG_STBC_PBC_RST_DELAY_CNT			(*((vu32 *)ADR_STBC_PBC_RST_DELAY_CNT		))       //REG_STBC_PBC_RST_DELAY_CNT
#define	REG_STBC_PBC_INPUT_CTRL_SIGNAL		(*((vu32 *)ADR_STBC_PBC_INPUT_CTRL_SIGNAL	))       //REG_STBC_PBC_INPUT_CTRL_SIGNAL
#define	REG_STBC_PBC_VER_EDITION			(*((vu32 *)ADR_STBC_PBC_VER_EDITION			))       //REG_STBC_PBC_LD0_INI_STS
#define	REG_STBC_IO_LEV_INPUT_OUTPUT_SEL	(*((vu32 *)ADR_STBC_IO_LEV_INPUT_OUTPUT_SEL	))       //REG_STBC_IO_LEV_INPUT_OUTPUT_SEL
#define	REG_STBC_IO_DIR_SEL					(*((vu32 *)ADR_STBC_IO_DIR_SEL				))       //REG_STBC_IO_DIR_SEL
#define	REG_STBC_GPIO_FUN_SEL				(*((vu32 *)ADR_STBC_GPIO_FUN_SEL			))       //REG_STBC_GPIO_FUN_SEL

/*******************************************************************************************/
/* CEC REG */
#define	REG_STBC_CEC_CTRL				(*((vu32 *)ADR_STBC_CEC_CTRL			    ))       //REG_STBC_CEC_CTRL
#define	REG_STBC_CEC_CLK_BASE1			(*((vu32 *)ADR_STBC_CEC_CLK_BASE1			))       //REG_STBC_CEC_CLK_BASE1
#define	REG_STBC_CEC_CLK_BASE2			(*((vu32 *)ADR_STBC_CEC_CLK_BASE2			))       //REG_STBC_CEC_CLK_BASE2
#define	REG_STBC_CEC_SIGFREE_CNT1		(*((vu32 *)ADR_STBC_CEC_SIGFREE_CNT1	    ))       //REG_STBC_CEC_SIGFREE_CNT1
#define	REG_STBC_CEC_SIGFREE_CNT2		(*((vu32 *)ADR_STBC_CEC_SIGFREE_CNT2	    ))       //REG_STBC_CEC_SIGFREE_CNT2
#define	REG_STBC_CEC_TX_RISEEDGE		(*((vu32 *)ADR_STBC_CEC_TX_RISEEDGE			))       //REG_STBC_CEC_TX_RISEEDGE
#define	REG_STBC_CEC_TX_FALLEDGE		(*((vu32 *)ADR_STBC_CEC_TX_FALLEDGE			))       //REG_STBC_CEC_TX_FALLEDGE
#define	REG_STBC_CEC_RX_STARTBIT_EDGE	(*((vu32 *)ADR_STBC_CEC_RX_STARTBIT_EDGE	))       //REG_STBC_CEC_RX_STARTBIT_EDGE
#define	REG_STBC_CEC_RX_DATABIT_EDGE	(*((vu32 *)ADR_STBC_CEC_RX_DATABIT_EDGE		))       //REG_STBC_CEC_RX_DATABIT_EDGE
#define	REG_STBC_CEC_RX_SAFE_SMPDATA	(*((vu32 *)ADR_STBC_CEC_RX_SAFE_SMPDATA		))       //REG_STBC_CEC_RX_SAFE_SMPDATA
#define	REG_STBC_CEC_DEGLITCH_FTR		(*((vu32 *)ADR_STBC_CEC_DEGLITCH_FTR	    ))       //REG_STBC_CEC_DEGLITCH_FTR
#define	REG_STBC_CEC_RX_LOWERR_LSB		(*((vu32 *)ADR_STBC_CEC_RX_LOWERR_LSB		))       //REG_STBC_CEC_RX_LOWERR_LSB
#define	REG_STBC_CEC_RX_LOWERR_MSB		(*((vu32 *)ADR_STBC_CEC_RX_LOWERR_MSB		))       //REG_STBC_CEC_RX_LOWERR_MSB
#define	REG_STBC_CEC_INT_EN				(*((vu32 *)ADR_STBC_CEC_INT_EN				))       //REG_STBC_CEC_INT_EN
#define	REG_STBC_CEC_INT_DIS			(*((vu32 *)ADR_STBC_CEC_INT_DIS				))       //REG_STBC_CEC_INT_DIS
#define	REG_STBC_CEC_INT_FLAG			(*((vu32 *)ADR_STBC_CEC_INT_FLAG		    ))       //REG_STBC_CEC_INT_FLAG
#define	REG_STBC_CEC_DBG				(*((vu32 *)ADR_STBC_CEC_DBG					))       //REG_STBC_CEC_DBG
#define	REG_STBC_CEC_RX_ADDR_EN1		(*((vu32 *)ADR_STBC_CEC_RX_ADDR_EN1			))       //REG_STBC_CEC_RX_ADDR_EN1
#define	REG_STBC_CEC_RX_ADDR_EN2		(*((vu32 *)ADR_STBC_CEC_RX_ADDR_EN2			))       //REG_STBC_CEC_RX_ADDR_EN2
#define	REG_STBC_CEC_RX_FRAME_LEN		(*((vu32 *)ADR_STBC_CEC_RX_FRAME_LEN	    ))       //REG_STBC_CEC_RX_FRAME_LEN
#define	REG_STBC_CEC_TX_FRAME_LEN		(*((vu32 *)ADR_STBC_CEC_TX_FRAME_LEN	    ))       //REG_STBC_CEC_TX_FRAME_LEN
#define	REG_STBC_CEC_FTR				(*((vu32 *)ADR_STBC_CEC_FTR					))       //REG_STBC_CEC_FTR
#define	REG_STBC_CEC_TX_DATA0			(*((vu32 *)ADR_STBC_CEC_TX_DATA0		    ))       //REG_STBC_CEC_TX_DATA0
#define	REG_STBC_CEC_TX_DATA1			(*((vu32 *)ADR_STBC_CEC_TX_DATA1		    ))       //REG_STBC_CEC_TX_DATA1
#define	REG_STBC_CEC_TX_DATA2			(*((vu32 *)ADR_STBC_CEC_TX_DATA2		    ))       //REG_STBC_CEC_TX_DATA2
#define	REG_STBC_CEC_TX_DATA3			(*((vu32 *)ADR_STBC_CEC_TX_DATA3		    ))       //REG_STBC_CEC_TX_DATA3
#define	REG_STBC_CEC_TX_DATA4			(*((vu32 *)ADR_STBC_CEC_TX_DATA4		    ))       //REG_STBC_CEC_TX_DATA4
#define	REG_STBC_CEC_TX_DATA5			(*((vu32 *)ADR_STBC_CEC_TX_DATA5		    ))       //REG_STBC_CEC_TX_DATA5
#define	REG_STBC_CEC_TX_DATA6			(*((vu32 *)ADR_STBC_CEC_TX_DATA6		    ))       //REG_STBC_CEC_TX_DATA6
#define	REG_STBC_CEC_TX_DATA7			(*((vu32 *)ADR_STBC_CEC_TX_DATA7		    ))       //REG_STBC_CEC_TX_DATA7
#define	REG_STBC_CEC_TX_DATA8			(*((vu32 *)ADR_STBC_CEC_TX_DATA8		    ))       //REG_STBC_CEC_TX_DATA8
#define	REG_STBC_CEC_TX_DATA9			(*((vu32 *)ADR_STBC_CEC_TX_DATA9		    ))       //REG_STBC_CEC_TX_DATA9
#define	REG_STBC_CEC_TX_DATA10			(*((vu32 *)ADR_STBC_CEC_TX_DATA10			))       //REG_STBC_CEC_TX_DATA10
#define	REG_STBC_CEC_TX_DATA11			(*((vu32 *)ADR_STBC_CEC_TX_DATA11			))       //REG_STBC_CEC_TX_DATA11
#define	REG_STBC_CEC_TX_DATA12			(*((vu32 *)ADR_STBC_CEC_TX_DATA12			))       //REG_STBC_CEC_TX_DATA12
#define	REG_STBC_CEC_TX_DATA13			(*((vu32 *)ADR_STBC_CEC_TX_DATA13			))       //REG_STBC_CEC_TX_DATA13
#define	REG_STBC_CEC_TX_DATA14			(*((vu32 *)ADR_STBC_CEC_TX_DATA14			))       //REG_STBC_CEC_TX_DATA14
#define	REG_STBC_CEC_TX_DATA15			(*((vu32 *)ADR_STBC_CEC_TX_DATA15			))       //REG_STBC_CEC_TX_DATA15
#define	REG_STBC_CEC_TX_DATA16			(*((vu32 *)ADR_STBC_CEC_TX_DATA16			))       //REG_STBC_CEC_TX_DATA16
#define	REG_STBC_CEC_RX_DATA0			(*((vu32 *)ADR_STBC_CEC_RX_DATA0		    ))       //REG_STBC_CEC_RX_DATA0
#define	REG_STBC_CEC_RX_DATA1			(*((vu32 *)ADR_STBC_CEC_RX_DATA1		    ))       //REG_STBC_CEC_RX_DATA1
#define	REG_STBC_CEC_RX_DATA2			(*((vu32 *)ADR_STBC_CEC_RX_DATA2		    ))       //REG_STBC_CEC_RX_DATA2
#define	REG_STBC_CEC_RX_DATA3			(*((vu32 *)ADR_STBC_CEC_RX_DATA3		    ))       //REG_STBC_CEC_RX_DATA3
#define	REG_STBC_CEC_RX_DATA4			(*((vu32 *)ADR_STBC_CEC_RX_DATA4		    ))       //REG_STBC_CEC_RX_DATA4
#define	REG_STBC_CEC_RX_DATA5			(*((vu32 *)ADR_STBC_CEC_RX_DATA5		    ))       //REG_STBC_CEC_RX_DATA5
#define	REG_STBC_CEC_RX_DATA6			(*((vu32 *)ADR_STBC_CEC_RX_DATA6		    ))       //REG_STBC_CEC_RX_DATA6
#define	REG_STBC_CEC_RX_DATA7			(*((vu32 *)ADR_STBC_CEC_RX_DATA7		    ))       //REG_STBC_CEC_RX_DATA7
#define	REG_STBC_CEC_RX_DATA8			(*((vu32 *)ADR_STBC_CEC_RX_DATA8		    ))       //REG_STBC_CEC_RX_DATA8
#define	REG_STBC_CEC_RX_DATA9			(*((vu32 *)ADR_STBC_CEC_RX_DATA9		    ))       //REG_STBC_CEC_RX_DATA9
#define	REG_STBC_CEC_RX_DATA10			(*((vu32 *)ADR_STBC_CEC_RX_DATA10			))       //REG_STBC_CEC_RX_DATA10
#define	REG_STBC_CEC_RX_DATA11			(*((vu32 *)ADR_STBC_CEC_RX_DATA11			))       //REG_STBC_CEC_RX_DATA11
#define	REG_STBC_CEC_RX_DATA12			(*((vu32 *)ADR_STBC_CEC_RX_DATA12			))       //REG_STBC_CEC_RX_DATA12
#define	REG_STBC_CEC_RX_DATA13			(*((vu32 *)ADR_STBC_CEC_RX_DATA13			))       //REG_STBC_CEC_RX_DATA13
#define	REG_STBC_CEC_RX_DATA14			(*((vu32 *)ADR_STBC_CEC_RX_DATA14			))       //REG_STBC_CEC_RX_DATA14
#define	REG_STBC_CEC_RX_DATA15			(*((vu32 *)ADR_STBC_CEC_RX_DATA15			))       //REG_STBC_CEC_RX_DATA15
#define	REG_STBC_CEC_RX_DATA16			(*((vu32 *)ADR_STBC_CEC_RX_DATA16			))       //REG_STBC_CEC_RX_DATA16

/*******************************************************************************************/
/* RTC */
//REG_STBC_RTC_CNT Register Bit define
#define STBC_RTC_CNT_SEC_MSK					(0x0000003F)	//bit5~0
#define STBC_RTC_CNT_MIN_MSK					(0x00000FC0)	//bit11~6
#define STBC_RTC_CNT_HOUR_MSK					(0x0001F000)	//bit16~12
#define STBC_RTC_CNT_DAY_MSK					(0xFFFE0000)	//bit31~17
//REG_STBC_RTC_CNT_CTRL Register Bit define
#define BIT_STBC_RTC_CNT_CTRL					(0x00000001)	//bit0
#define STBC_RTC_CLK_SEL_MSK					(0x00000600)	//bit10~9
//REG_STBC_RTC_INT_CTRL Register Bit define
#define BIT_STBC_RTC_INT_CTRL_SEC				(0x00000001)	//bit0
#define BIT_STBC_RTC_INT_CTRL_MIN				(0x00000002)	//bit1
#define BIT_STBC_RTC_INT_CTRL_HOUR				(0x00000004)	//bit2
#define BIT_STBC_RTC_INT_CTRL_DAY				(0x00000008)	//bit3
#define STBC_RTC_INT_CTRL_MSK					(0x0000000F)	//bit3~0
#define STBC_RTC_CLK_CNT_MSK					(0xFFFFFF00)	//bit31~8
//REG_STBC_RTC_INT_STS Register Bit define
#define BIT_STBC_RTC_INT_STS_SEC				(0x00000001)	//bit0
#define BIT_STBC_RTC_INT_STS_MIN				(0x00000002)	//bit1
#define BIT_STBC_RTC_INT_STS_HOUR				(0x00000004)	//bit2
#define BIT_STBC_RTC_INT_STS_DAY				(0x00000008)	//bit3
//REG_STBC_RTC_WRITE_PROTECT Register Bit define
#define STBC_RTC_WRITE_PROTECT_MSK				(0x000FFFFF)	//bit19~0
//REG_STBC_RTC_ITL_SRC_DIV Register Bit define
#define STBC_RTC_ITL_SRC_DIV_MSK				(0x0000FFFF)	//bit15~0
//REG_RTC_RESERVED Register Bit define
#define STBC_RTC_RESERVED_MSK					(0xFFFFFFFF)	//bit31~0
//REG_STBC_RTC_DOWN_CNT_CTRL Register Bit define
#define BIT_STBC_RTC_DOWN_CNT_CTRL				(0x00000001)	//bit0
#define BIT_STBC_RTC_WAKEUP_EN					(0x00000002)	//bit1
#define STBC_RTC_DOWN_CNT_CLK_MSK				(0xFFFFFF00)	//bit31~8
//REG_STBC_RTC_DOWN_CNT_NUM_CTRL Register Bit define
#define STBC_RTC_DOWN_CNT_NUM_CTRL_MSK			(0xFFFFFFFF)	//bit31~0
//REG_STBC_INT_GROUP Register Bit define
#define BIT_STBC_INT_GROUP_RTC					(0x00000001)	//bit0
#define BIT_STBC_INT_GROUP_CEC					(0x00000002)	//bit1
#define BIT_STBC_INT_GROUP_IR					(0x00000004)	//bit2
#define BIT_STBC_INT_GROUP_PWSW					(0x00000008)	//bit3
#define BIT_STBC_INT_GROUP_HPD					(0x00000010)	//bit4

/*******************************************************************************************/
/* IR */
//REG_STBC_IR_DEC_CTRL Register Bit define
#define BIT_STBC_IR_HEAD_DET_INT_EN				(0x00000001)	//bit0
#define BIT_STBC_IR_REPCOD_DET_INT_EN			(0x00000002)	//bit1
#define BIT_STBC_IR_INVCOD_LEN_DET_INT_EN		(0x00000004)	//bit2
#define BIT_STBC_IR_VALCOD_LEN_DET_INT_EN		(0x00000008)	//bit3
#define BIT_STBC_IR_RST_FIFO					(0x00000010)	//bit4
#define BIT_STBC_SWIR_RISEEDG_INT_EN			(0x00000020)	//bit5
#define BIT_STBC_SWIR_FALLEDG_INT_EN			(0x00000040)	//bit6
#define STBC_IR_INTR_MSK						(0x0000007F)	//bit6~0
//REG_STBC_IR_DEC_STS Register Bit define
#define BIT_STBC_IR_HEAD_DET_INT				(0x00000001)	//bit0
#define BIT_STBC_IR_REPCOD_DET_INT				(0x00000002)	//bit1
#define BIT_STBC_IR_INVCOD_LEN_DET_INT			(0x00000004)	//bit2
#define BIT_STBC_IR_VALCOD_LEN_DET_INT			(0x00000008)	//bit3
#define BIT_STBC_IR_TIMING_WIN_INT				(0x00000010)	//bit4
#define BIT_STBC_IR_FIFO_OV_INT					(0x00000020)	//bit5
#define STBC_IR_VALETYCNT_FIFO_MSK				(0x000001C0)	//bit8~6
#define BIT_STBC_IR_RISEEDGE_DET_INT			(0x00000200)	//bit9
#define BIT_STBC_IR_FALLEDGE_DET_INT			(0x00000400)	//bit10
//REG_STBC_IR_FORMAT Register Bit define
#define STBC_IR_CODE_LEN_MSK					(0x0000001F)	//bit4~0
#define STBC_IR_MODULATION_MSK					(0x00000300)	//bit9~8
#define BIT_STBC_IR_REPCOD_DET_EN				(0x00000400)	//bit10
#define BIT_STBC_IR_WAKEUP_DET_EN				(0x00000800)	//bit11
#define BIT_STBC_IR_ANYKEY_WAKEUP_DET_EN		(0x00001000)	//bit12
#define BIT_STBC_IR_INVPOL_EN					(0x00002000)	//bit13
#define BIT_STBC_IR_R_TIMING_WIN_EN				(0x00004000)	//bit14
#define STBC_IR_TIMING_MSK						(0x03FF0000)	//bit25~16
//REG_STBC_IR_HEAD_PULSE_TIME Register Bit define
#define STBC_IR_HEAD_PULSE_MIN_MSK				(0x000003FF)	//bit9~0
#define STBC_IR_HEAD_PULSE_MAX_MSK				(0x03FF0000)	//bit25~16
//REG_STBC_IR_HEAD_SPACE_TIME Register Bit define
#define STBC_IR_HEAD_SPACE_MIN_MSK				(0x000003FF)	//bit9~0
#define STBC_IR_HEAD_SPACE_MAX_MSK				(0x03FF0000)	//bit25~16
//REG_STBC_IR_LOG0_PULSE_TIME Register Bit define
#define STBC_IR_LOG0_PULSE_MIN_MSK				(0x000000FF)	//bit7~0
#define STBC_IR_LOG0_PULSE_MAX_MSK				(0x00FF0000)	//bit23~16
//REG_STBC_IR_LOG0_SPACE_TIME Register Bit define
#define STBC_IR_LOG0_SPACE_MIN_MSK				(0x000000FF)	//bit7~0
#define STBC_IR_LOG0_SPACE_MAX_MSK				(0x00FF0000)	//bit23~16
//REG_STBC_IR_LOG1_PULSE_TIME Register Bit define
#define STBC_IR_LOG1_PULSE_MIN_MSK				(0x000000FF)	//bit7~0
#define STBC_IR_LOG1_PULSE_MAX_MSK				(0x00FF0000)	//bit23~16
//REG_STBC_IR_LOG1_SPACE_TIME Register Bit define
#define STBC_IR_LOG1_SPACE_MIN_MSK				(0x000000FF)	//bit7~0
#define STBC_IR_LOG1_SPACE_MAX_MSK				(0x00FF0000)	//bit23~16
//REG_STBC_IR_GLITCH_TIME Register Bit define
#define STBC_IR_GLITCH_PULSE_MIN_MSK			(0x000000FF)	//bit7~0
//REG_STBC_IR_REPCOD_PULSE_TIME Register Bit define
#define STBC_IR_REPCOD_PULSE_MIN_MSK			(0x000003FF)	//bit9~0
#define STBC_IR_REPCOD_PULSE_MAX_MSK			(0x03FF0000)	//bit25~16
//REG_STBC_IR_REPCOD_SPACE_TIME Register Bit define
#define STBC_IR_REPCOD_SPACE_MIN_MSK			(0x000003FF)	//bit9~0
#define STBC_IR_REPCOD_SPACE_MAX_MSK			(0x03FF0000)	//bit25~16
//REG_STBC_IR_REC_LOW_WORD_FIFO Register Bit define
#define STBC_IR_REC_LOW_WORD_FIFO_MSK			(0xFFFFFFFF)	//bit31~0
//REG_STBC_IR_REC_HIGH_WORD_FIFO Register Bit define
#define STBC_IR_HEAD_DET_MSK					(0x00000001)	//bit0
#define BIT_STBC_IR_REPCOD_DET					(0x00000002)	//bit1
#define BIT_STBC_IR_INVCOD_LEN_DET				(0x00000004)	//bit2
#define BIT_STBC_IR_VALCOD_LEN_DET				(0x00000008)	//bit3
#define STBC_IR_HIGH_WORD_FIFO_MSK				(0x0000000F)	//bit3~0
//REG_STBC_IR_WAKEUP_LOW_WORD Register Bit define
#define STBC_IR_WAKEUP_CODE_MSK					(0xFFFFFFFF)	//bit31~0
//REG_STBC_PAD1 Register Bit define
#define BIT_STBC_CEC_PAD_PULLDOWN_EN			(0x00000001)	//bit0
#define BIT_STBC_CEC_PAD_PULLUP_EN				(0x00000002)	//bit1
#define STBC_CEC_PAD_MSK						(0x00000003)	//bit1~0
#define BIT_STBC_CEC_PAD_SLEW_RATE				(0x00000004)	//bit2
#define STBC_CEC_PAD_DRIVING_STRENGTH_MSK		(0x00000018)	//bit4~3
#define BIT_STBC_LED1_PAD_PULLDOWN_EN			(0x00000020)	//bit5
#define BIT_STBC_LED1_PAD_PULLUP_EN				(0x00000040)	//bit6
#define STBC_LED1_PAD_MSK						(0x00000060)	//bit6~5
#define BIT_STBC_LED1_PAD_SLEW_RATE				(0x00000080)	//bit7
#define STBC_LED1_PAD_DRIVING_STRENGTH_MSK		(0x00000300)	//bit9~8
#define BIT_STBC_LED2_PAD_PULLDOWN_EN			(0x00000400)	//bit10
#define BIT_STBC_LED2_PAD_PULLUP_EN				(0x00000800)	//bit11
#define STBC_LED2_PAD_MSK						(0x00000C00)	//bit11~10
#define BIT_STBC_LED2_PAD_SLEW_RATE				(0x00001000)	//bit12
#define STBC_LED2_PAD_DRIVING_STRENGTH_MSK		(0x00006000)	//bit14~13
#define BIT_STBC_IR_PAD_PULLDOWN_EN				(0x00008000)	//bit15
#define BIT_STBC_IR_PAD_PULLUP_EN				(0x00010000)	//bit16
#define STBC_IR_PAD_MSK							(0x00018000)	//bit16~15
#define BIT_STBC_IR_PAD_SLEW_RATE				(0x00020000)	//bit17
#define STBC_IR_PAD_DRIVING_STRENGTH_MSK		(0x000C0000)	//bit19~18
#define BIT_STBC_PWSW_PAD_PULLDOWN_EN			(0x00100000)	//bit20
#define BIT_STBC_PWSW_PAD_PULLUP_EN				(0x00200000)	//bit21
#define STBC_PWSW_PAD_MSK						(0x00300000)	//bit21~20
#define BIT_STBC_PWSW_PAD_SLEW_RATE				(0x00400000)	//bit22
#define STBC_PWSW_PAD_DRIVING_STRENGTH_MSK		(0x01800000)	//bit24~23
#define BIT_STBC_PWEN_PAD_PULLDOWN_EN			(0x02000000)	//bit25
#define BIT_STBC_PWEN_PAD_PULLUP_EN				(0x04000000)	//bit26
#define STBC_PWEN_PAD_MSK						(0x06000000)	//bit26~25
#define BIT_STBC_PWEN_PAD_SLEW_RATE				(0x08000000)	//bit27
#define STBC_PWEN_PAD_DRIVING_STRENGTH_MSK		(0x30000000)	//bit28~29
//REG_STBC_PAD2 Register Bit define
#define BIT_STBC_HOTPLUG_PAD_PULLDOWN_EN		(0x00000001)	//bit0
#define BIT_STBC_HOTPLUG_PAD_PULLUP_EN			(0x00000002)	//bit1
#define STBC_HPD_PAD_MSK						(0x00000003)	//bit1~0
#define BIT_STBC_HOTPLUG_PAD_SLEW_RATE			(0x00000004)	//bit2
#define STBC_HOTPLUG_PAD_DRIVING_STRENGTH_MSK	(0x00000018)	//bit4~3
//REG_STBC_IR_BIPHASE_TIME Register Bit define
#define STBC_IR_BIPHASE_TIME_MIN_MSK			(0x000000FF)	//bit7~0
#define STBC_IR_BIPHASE_TIME_MAX_MSK			(0x00FF0000)	//bit23~16

/*******************************************************************************************/
/* PBC */
//REG_STBC_PBC_CTRL_STS Register Bit define
#define BIT_STBC_PBC_PWEN_LEV					(0x00000001)	//bit0
#define BIT_STBC_PBC_PWSW_LEV					(0x00000002)	//bit1
#define BIT_STBC_PBC_PWSW_RISEEDGE_INTR_EN		(0x00000004)	//bit2
#define BIT_STBC_PBC_PWSW_FALLEDGE_INTR_EN		(0x00000008)	//bit3
#define BIT_STBC_PBC_PWEN_DISASSERT				(0x00000010)	//bit4
#define BIT_STBC_PBC_PWSW_RISEEDGE_INTR			(0x00000020)	//bit5
#define BIT_STBC_PBC_PWSW_FALLEDGE_INTR			(0x00000040)	//bit6
#define BIT_STBC_PBC_PWEN_SEL					(0x00000080)	//bit7
#define BIT_STBC_PBC_RST_IDENTIFY				(0x00000100)	//bit8
#define BIT_STBC_HOT_PLUG_RISEEDGE_INTR_EN		(0x00000200)	//bit9
#define BIT_STBC_HOT_PLUG_FALLEDGE_INTR_EN		(0x00000400)	//bit10
#define BIT_STBC_HOT_PLUG_RISEEDGE_INTR			(0x00000800)	//bit11
#define BIT_STBC_HOT_PLUG_FALLEDGE_INTR			(0x00001000)	//bit12

//REG_STBC_PBC_RST_DELAY_CNT Register Bit define
#define STBC_PBC_RST_DELAY_CNT_MSK				(0xFFFFFFFF)	//bit31~0
//REG_STBC_PBC_INPUT_CTRL_SIGNAL Register Bit define
#define STBC_PBC_INPUT_CTRL_SIGNAL_MSK			(0x000000FF)	//bit7~0
//REG_STBC_PBC_VER EDITION Register Bit define
#define STBC_PBC_LDO_INI_STS_MSK				(0x00000007)	//bit2~0

//REG_STBC_IO_LEV_INPUT_OUTPUT_SEL Register Bit define
#define BIT_STBC_PWEN_INPUT						(0x00000001)	//bit0
#define BIT_STBC_PWSW_INPUT						(0x00000002)	//bit1
#define BIT_STBC_IR_INPUT						(0x00000004)	//bit2
#define BIT_STBC_LED2_INPUT						(0x00000008)	//bit3
#define BIT_STBC_LED1_INPUT						(0x00000010)	//bit4
#define BIT_STBC_CEC_I_INPUT					(0x00000020)	//bit5
#define BIT_STBC_HOTPLUG_I_INPUT				(0x00000040)	//bit6
#define STBC_PAD_I_LEV_MSK						(0x0000007F)	//bit6~0

#define BIT_STBC_PWEN_O_LEV						(0x00000100)	//bit8
#define BIT_STBC_PWSW_O_LEV						(0x00000200)	//bit9
#define BIT_STBC_IR_O_LEV						(0x00000400)	//bit10
#define BIT_STBC_GPIO1_O_LEV					(0x00000800)	//bit11
#define BIT_STBC_GPIO2_O_LEV					(0x00001000)	//bit12
#define BIT_STBC_CEC_O_LEV						(0x00002000)	//bit13
#define BIT_STBC_HOTPLUG_O_LEV					(0x00004000)	//bit14
#define STBC_PAD_O_LEV_MSK						(0x00007F00)	//bit14~8

//REG_STBC_IO_DIR_SEL Register Bit define
#define BIT_STBC_PAD_PWEN_OE					(0x00000001)	//bit0
#define BIT_STBC_PAD_PWSW_OE					(0x00000002)	//bit1
#define BIT_STBC_PAD_IR_OE						(0x00000004)	//bit2
#define BIT_STBC_PAD_GPIO1_OE					(0x00000008)	//bit3
#define BIT_STBC_PAD_GPIO2_OE					(0x00000010)	//bit4
#define BIT_STBC_PAD_CEC_OEN					(0x00000020)	//bit5
#define BIT_STBC_PAD_HOTPLUG_OE					(0x00000040)	//bit6
#define STBC_IO_DIR_SEL_MSK						(0x0000007F)	//bit6~0

//REG_STBC_GPIO_FUN_SEL Register Bit define
#define BIT_STBC_SEL_FUN_PWEN					(0x00000001)	//bit0
#define BIT_STBC_SEL_FUN_PWSW					(0x00000002)	//bit1
#define BIT_STBC_SEL_FUN_IR						(0x00000004)	//bit2
#define BIT_STBC_SEL_FUN_CEC					(0x00000008)	//bit3
#define BIT_STBC_SEL_FUN_HOTPLUG				(0x00000010)	//bit4
#define STBC_GPIO_FUN_SEL_MSK					(0x0000001F)	//bit4~0, select STBC function or STBC IO

#define BIT_STBC_SEL_GPIO_PWEN					(0x00000100)	//bit8
#define BIT_STBC_SEL_GPIO_PWSW					(0x00000200)	//bit9
#define BIT_STBC_SEL_GPIO_IR					(0x00000400)	//bit10
#define BIT_STBC_SEL_GPIO_GPIO1					(0x00000800)	//bit11
#define BIT_STBC_SEL_GPIO_GPIO2					(0x00001000)	//bit12
#define BIT_STBC_SEL_GPIO_CEC					(0x00002000)	//bit13
#define BIT_STBC_SEL_GPIO_HOTPLUG				(0x00004000)	//bit14
#define STBC_GPIO_STBC_LEADERSHIP_MSK			(0x00007F00)	//bit14~8, select normal IO or STBC IO

/*******************************************************************************************/
/* CEC */
//REG_STBC_CEC_CTRL Register Bit define
#define BIT_STBC_CEC_EN							(0x00000001)	//bit0
#define STBC_CEC_LOCAL_ADDR_MSK					(0x000000F0)	//bit7~4
//REG_STBC_CEC_CLK_BASE1 Register Bit define
#define STBC_CEC_CLK1_MSK						(0x000000FF)	//bit7~0
//REG_STBC_CEC_CLK_BASE2 Register Bit define
#define STBC_CEC_CLK2_MSK						(0x000000FF)	//bit7~0
//REG_STBC_CEC_SIGFREE_CNT1 Register Bit define
#define STBC_CEC_FREE_CNT2_MSK					(0x0000000F)	//bit3~0
#define STBC_CEC_FREE_CMT1_MSK					(0x000000F0)	//bit7~4
//REG_STBC_CEC_SIGFREE_CNT2 Register Bit define
#define STBC_CEC_TX_RETRY_CNT_MSK				(0x0000000F)	//bit3~0
#define STBC_CEC_FREE_CMT3_MSK					(0x000000F0)	//bit7~4
//REG_STBC_CEC_TX_RISEEDGE Register Bit define
#define STBC_CEC_TX_F_OFFSET_MSK				(0x000000FF)	//bit7~0
//REG_STBC_CEC_TX_FALLEDGE Register Bit define
#define STBC_CEC_TX_R_OFFSET_MSK				(0x000000FF)	//bit7~0
//REG_STBC_CEC_RX_STARTBIT_EDGE Register Bit define
#define STBC_CEC_RX_S_OFFSET_MSK				(0x000000FF)	//bit7~0
//REG_STBC_CEC_RX_DATABIT_EDGE Register Bit define
#define STBC_CEC_RX_D_OFFSET_MSK				(0x000000FF)	//bit7~0
//REG_STBC_CEC_RX_SAFE_SMPDATA Register Bit define
#define STBC_CEC_RX_SMP_OFFSET_MSK				(0x000000FF)	//bit7~0
//REG_STBC_CEC_DEGLITCH_FTR Register Bit define
#define STBC_CEC_DEGLITCH_MSK					(0x0000000F)	//bit3~0
//REG_STBC_CEC_RX_LOWERR_LSB Register Bit define
#define STBC_CEC_RX_ERR_LOW_MSK					(0x000000FF)	//bit7~0
//REG_STBC_CEC_RX_LOWERR_MSB Register Bit define
#define BIT_STBC_CEC_RX_ERR_LPW_H				(0x00000001)	//bit0
//REG_STBC_CEC_INT_EN Register Bit define
#define BIT_STBC_CEC_INT_RX_EN					(0x00000001)	//bit0
#define BIT_STBC_CEC_INT_TX_EN					(0x00000002)	//bit1
#define BIT_STBC_CEC_INT_RF_EN					(0x00000004)	//bit2
#define BIT_STBC_CEC_LOST_EN					(0x00000008)	//bit3
#define BIT_STBC_CEC_RXOV_EN					(0x00000010)	//bit4
#define BIT_STBC_CEC_ERR_EN						(0x00000020)	//bit5
#define STBC_CEC_INT_MSK						(0x0000003F)	//bit5~0
//REG_STBC_CEC_INT_DIS Register Bit define
#define BIT_STBC_CEC_INT_RX_DIS					(0x00000001)	//bit0
#define BIT_STBC_CEC_INT_TX_DIS					(0x00000002)	//bit1
#define BIT_STBC_CEC_INT_RF_DIS					(0x00000004)	//bit2
#define BIT_STBC_CEC_LOST_DIS					(0x00000008)	//bit3
#define BIT_STBC_CEC_RXOV_DIS					(0x00000010)	//bit4
#define BIT_STBC_CEC_ERR_DIS					(0x00000020)	//bit5
//REG_STBC_CEC_INT_FLAG Register Bit define
#define BIT_STBC_CEC_INT_RX						(0x00000001)	//bit0
#define BIT_STBC_CEC_INT_TX						(0x00000002)	//bit1
#define BIT_STBC_CEC_INT_RF						(0x00000004)	//bit2
#define BIT_STBC_CEC_LOST						(0x00000008)	//bit3
#define BIT_STBC_CEC_RXOV						(0x00000010)	//bit4
#define BIT_STBC_CEC_ERR						(0x00000020)	//bit5
//REG_STBC_CEC_DBG Register Bit define
#define BIT_STBC_CEC_DIS_ACK					(0x00000001)	//bit0
#define BIT_STBC_CEC_RX_HOLD					(0x00000002)	//bit1
#define BIT_STBC_CEC_WAKEUP_EN					(0x00000004)	//bit2
#define BIT_STBC_CEC_RX_LEN_17					(0x00000020)	//bit5
#define BIT_STBC_CEC_DIS_RX_CHK					(0x00000040)	//bit6
#define BIT_STBC_CEC_DIS_RX_ERR					(0x00000080)	//bit7
//REG_STBC_CEC_RX_ADDR_EN1 Bit define
#define BIT_STBC_CEC_EN_RX_ADD_0				(0x00000001)	//bit0
#define BIT_STBC_CEC_EN_RX_ADD_1				(0x00000002)	//bit1
#define BIT_STBC_CEC_EN_RX_ADD_2				(0x00000004)	//bit2
#define BIT_STBC_CEC_EN_RX_ADD_3				(0x00000008)	//bit3
#define BIT_STBC_CEC_EN_RX_ADD_4				(0x00000010)	//bit4
#define BIT_STBC_CEC_EN_RX_ADD_5				(0x00000020)	//bit5
#define BIT_STBC_CEC_EN_RX_ADD_6				(0x00000040)	//bit6
#define BIT_STBC_CEC_EN_RX_ADD_7				(0x00000080)	//bit7
#define STBC_CEC_EN_RX_ADD_MSK1					(0x000000FF)	//bit7~0
//REG_STBC_CEC_RX_ADDR_EN2 Bit define
#define BIT_STBC_CEC_EN_RX_ADD_8				(0x00000001)	//bit0
#define BIT_STBC_CEC_EN_RX_ADD_9				(0x00000002)	//bit1
#define BIT_STBC_CEC_EN_RX_ADD_A				(0x00000004)	//bit2
#define BIT_STBC_CEC_EN_RX_ADD_B				(0x00000008)	//bit3
#define BIT_STBC_CEC_EN_RX_ADD_C				(0x00000010)	//bit4
#define BIT_STBC_CEC_EN_RX_ADD_D				(0x00000020)	//bit5
#define BIT_STBC_CEC_EN_RX_ADD_E				(0x00000040)	//bit6
#define BIT_STBC_CEC_EN_RX_BROADCAST			(0x00000080)	//bit7
#define STBC_CEC_EN_RX_ADD_MSK2					(0x000000FF)	//bit7~0
//REG_STBC_CEC_RX_FRAME_LEN Register Bit define
#define STBC_CEC_RX_LEN_MSK						(0x0000001F)	//bit4~0
//REG_STBC_CEC_TX_FRAME_LEN Register Bit define
#define STBC_CEC_TX_LEN_MSK						(0x0000001F)	//bit4~0
//REG_STBC_CEC_FTR Register Bit define
#define STBC_CEC_FTR_MSK						(0x0000000F)	//bit3~0
#define STBC_CEC_ARBIT_RANG_MSK					(0x000000F0)	//bit7~4
//REG_STBC_CEC_TX_DATA0 Register Bit define
#define STBC_CEC_TX_DATA0_DEST_MSK				(0x0000000F)	//bit3~0
#define STBC_CEC_TX_DATA0_INI_MSK				(0x000000F0)	//bit7~4
#define CEC_TX_DATA0_MSK						(0x000000FF)	//bit7~0
//REG_STBC_CEC_TX_DATA1~16 Register Bit define
#define STBC_CEC_TX_DATAN_MSK					(0x000000FF)	//bit7~0
//REG_STBC_CEC_RX_DATA0 Register Bit define
#define STBC_CEC_RX_DATA0_DEST_MSK				(0x0000000F)	//bit3~0
#define STBC_CEC_RX_DATA0_INI_MSK				(0x000000F0)	//bit7~4
#define CEC_RX_DATA0_MSK						(0x000000FF)	//bit7~0
//REG_STBC_CEC_RX_DATA1~16 Register Bit define
#define STBC_CEC_RX_DATAN_MSK					(0x000000FF)	//bit7~0

/*******************************************************************************************/
// IO Direction define
#define DRV_STBC_PAD_PWEN_OE					(0x00000001)	//bit0
#define DRV_STBC_PAD_PWSW_OE					(0x00000002)	//bit1
#define DRV_STBC_PAD_IR_OE						(0x00000004)	//bit2
#define DRV_STBC_PAD_GPIO1_OE					(0x00000008)	//bit3
#define DRV_STBC_PAD_GPIO2_OE					(0x00000010)	//bit4
#define DRV_STBC_PAD_CEC_OEN					(0x00000020)	//bit5
#define DRV_STBC_PAD_HOTPLUG_OE					(0x00000040)	//bit6
//STBC GPIO Function Select define
#define DRV_STBC_SEL_FUN_PWEN					(0x00000001)	//bit0
#define DRV_STBC_SEL_FUN_PWSW					(0x00000002)	//bit1
#define DRV_STBC_SEL_FUN_IR						(0x00000004)	//bit2
#define DRV_STBC_SEL_FUN_CEC					(0x00000008)	//bit3
#define DRV_STBC_SEL_FUN_HOTPLUG				(0x00000010)	//bit4
//STBC Leadership define
#define DRV_STBC_SEL_GPIO_PWEN					(0x00000100)	//bit8
#define DRV_STBC_SEL_GPIO_PWSW					(0x00000200)	//bit9
#define DRV_STBC_SEL_GPIO_IR					(0x00000400)	//bit10
#define DRV_STBC_SEL_GPIO_GPIO1					(0x00000800)	//bit11
#define DRV_STBC_SEL_GPIO_GPIO2					(0x00001000)	//bit12
#define DRV_STBC_SEL_GPIO_CEC					(0x00002000)	//bit13
#define DRV_STBC_SEL_GPIO_HOTPLUG				(0x00004000)	//bit14

#endif  //(CONFIG_CHIP_MODLE == NT78310)

#endif /* __REG_DRV_STBC_H__ */


